name: Sync Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Upstream
        uses: ikxin/sync-upstream@main
        with:
          github_token: ${{ secrets.SYNC_TOKEN }}
          target_repository: "zhcndoc/unocss"
          target_branch: "upstream"
          upstream_repository: "unocss/unocss"
          upstream_branch: "main"

      - name: Sync Tags
        run: |
          git fetch upstream --tags
          git push origin --tags --force
